name: "🐳 Docker Build & Publish"

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    name: "🧪 Run Tests"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      version: ${{ steps.utility_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get JackboxUtility Version
        id: utility_version
        run: |
          VERSION=$(curl -sL https://api.github.com/repos/JackboxUtility/JackboxUtility/releases/latest | jq -r .tag_name)
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "Found JackboxUtility version: ${VERSION}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ghcr.io/${{ github.repository_owner_id }}/${{ github.event.repository.name }}-test:${{ steps.utility_version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            maintainer=${{ github.actor }}
            org.opencontainers.image.version=${{ steps.utility_version.outputs.version }}

      - name: Run Critical Tests
        run: |
          echo "Starting container for critical tests..."
          docker run -d --name jackbox-utility \
            ghcr.io/${{ github.repository_owner_id }}/${{ github.event.repository.name }}-test:${{ steps.utility_version.outputs.version }}

          # Wait for container to start (max 30 seconds)
          for i in {1..6}; do
            if docker ps -a --filter "name=jackbox-utility" --format "{{.Status}}" | grep -q "Up"; then
              echo "✅ Container started successfully"
              break
            fi
            if [ $i -eq 6 ]; then
              echo "❌ Container failed to start"
              docker logs jackbox-utility
              exit 1
            fi
            echo "Waiting for container... (attempt $i/6)"
            sleep 5
          done

          echo "Verifying critical components..."
          
          # Check if JackboxUtility executable exists
          if ! docker exec jackbox-utility test -f /opt/jackbox-utility/JackboxUtility; then
            echo "❌ JackboxUtility executable not found"
            exit 1
          fi
          echo "✅ JackboxUtility executable present"

          # Check if desktop entry exists
          if ! docker exec jackbox-utility test -f /usr/share/applications/jackbox-utility.desktop; then
            echo "❌ Desktop entry not found"
            exit 1
          fi
          echo "✅ Desktop entry exists"

          # Check for critical system dependencies
          echo "Checking system dependencies..."
          DEPS=("wget" "unzip")
          for dep in "${DEPS[@]}"; do
            if ! docker exec jackbox-utility which $dep > /dev/null 2>&1; then
              echo "❌ Required dependency '$dep' not found"
              exit 1
            fi
          done
          echo "✅ All required system dependencies present"
          
          echo "✅ All critical tests passed"

  publish:
    name: "📦 Build & Push Image"
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ needs.test.outputs.version }}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=ref,event=tag
          labels: |
            org.opencontainers.image.title=JackboxUtility Client
            org.opencontainers.image.description=JackboxUtility client as KASM workspace
            org.opencontainers.image.version=${{ needs.test.outputs.version }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.licenses=GPL-3.0

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 